-- SPECIALS
insert into comics values("42", "Special_Superman_Rebirth");
INSERT INTO Special_Superman_Rebirth VALUES("300", "01", "", "", "2.99");

insert into comics values("41", "Special_Action_Comics_Rebirth");
INSERT INTO Special_Action_Comics_Rebirth VALUES("296", "01", "", "", "2.99");


-- ANNUAL COMICS
insert into comics values("20", "Annual_Batman_Rebirth");
INSERT INTO Annual_Batman_Rebirth VALUES("159", "01", "Silent Night", "", "2.99");
INSERT INTO Annual_Batman_Rebirth VALUES("284", "02", "Date Night / Last Rites", "", "2.99");

insert into comics values("21", "Annual_Supergirl_Rebirth");
INSERT INTO Annual_Supergirl_Rebirth VALUES("216", "01", "The Girl of No Tomorrow Part 2", "", "2.99");

insert into comics values("22", "Annual_Batgirl_Rebirth");
INSERT INTO Annual_Batgirl_Rebirth VALUES("142", "01", "World's Finest; Rain Check", "", "2.99");

insert into comics values("23", "Annual_Wonder_Woman_Rebirth");
INSERT INTO Annual_Wonder_Woman_Rebirth VALUES("173", "01", "Wonder Woman Annual #1", "", "2.99");

insert into comics values("24", "Annual_The_Flash_Rebirth");
INSERT INTO Annual_The_Flash_Rebirth VALUES("288", "01", "The Flash Annual #1", "", "2.99");




-- ONE SHOTS
insert into comics values("27", "DC_Universe_Rebirth");
INSERT INTO DC_Universe_Rebirth VALUES("10", "1", "Green Lanterns", "Rebirth", "2.99");
INSERT INTO DC_Universe_Rebirth VALUES("4", "1", "Superman", "Rebirth", "2.99");
INSERT INTO DC_Universe_Rebirth VALUES("5", "1", "Batman", "Rebirth", "2.99");
INSERT INTO DC_Universe_Rebirth VALUES("6", "1", "Wonder Woman", "Rebirth", "2.99");
INSERT INTO DC_Universe_Rebirth VALUES("7", "1", "Aquaman", "Rebirth", "2.99");
INSERT INTO DC_Universe_Rebirth VALUES("1", "1", "DC Universe", "Rebirth", "2.99");
INSERT INTO DC_Universe_Rebirth VALUES("8", "1", "Green Arrow", "Rebirth", "2.99");
INSERT INTO DC_Universe_Rebirth VALUES("9", "1", "The Flash", "Rebirth", "2.99");
INSERT INTO DC_Universe_Rebirth VALUES("11", "1", "Titans", "Rebirth", "2.99");
INSERT INTO DC_Universe_Rebirth VALUES("12", "1", "Supergirl", "Rebirth", "1.49");
INSERT INTO DC_Universe_Rebirth VALUES("13", "1", "Teen Titans", "Rebirth", "1.49");
INSERT INTO DC_Universe_Rebirth VALUES("14", "1", "Justice League", "Rebirth", "2.99");
INSERT INTO DC_Universe_Rebirth VALUES("46", "1", "Nightwing", "Rebirth", "2.99");
INSERT INTO DC_Universe_Rebirth VALUES("47", "1", "Batgirl and the Birds of Prey", "Rebirth", "2.99");
INSERT INTO DC_Universe_Rebirth VALUES("56", "1", "Batman Beyond", "Rebirth", "1.49");


insert into comics values("9", "The_Flash_Rebirth");
INSERT INTO The_Flash_Rebirth VALUES("37", "01", "Lightning Strikes Twice Part 1: Deus Ex Machina", "", "2.99");
INSERT INTO The_Flash_Rebirth VALUES("144", "21", "The Button Part 2", "The Button", "1.79");

insert into comics values("11", "Detective_Comics_Rebirth");
INSERT INTO Detective_Comics_Rebirth VALUES("57", "941", "Night of the Monster Men Part 3", "Monster Men", "2.99");
INSERT INTO Detective_Comics_Rebirth VALUES("58", "942", "Night of the Monster Men Part 6", "Monster Men", "2.99");

insert into comics values("12", "Nightwing_Rebirth");
INSERT INTO Nightwing_Rebirth VALUES("59", "05", "Night of the Monster Men Part 2", "Monster Men", "2.99");
INSERT INTO Nightwing_Rebirth VALUES("60", "06", "Night of the Monster Men Part 5", "Monster Men", "2.99");

insert into comics values("14", "Trinity_Rebirth");
INSERT INTO Trinity_Rebirth VALUES("151", "08", "Superman: Reborn Aftermath: The Truth About Superman", "Superman: Reborn", "2.39");

insert into comics values("89", "Deathstroke_Rebirth");
INSERT INTO Deathstroke_Rebirth VALUES("179", "19", "The Lazarus Contract Part 3", "Lazarus Contract", "1.79");

insert into comics values("16", "Super_Sons_Rebirth");
INSERT INTO Super_Sons_Rebirth VALUES("282", "12", "Super Sons of Tomorrow Finale: Last Minute Saved", "Sons of Tomorrow", "2.39");
INSERT INTO Super_Sons_Rebirth VALUES("285", "11", "Super Sons of Tomorrow Part 2: Son Down", "Sons of Tomorrow", "2.39");

insert into comics values("19", "Titans_Rebirth");
INSERT INTO Titans_Rebirth VALUES("186", "11", "The Lazarus Contract Part 1", "Lazarus Contract", "2.39");

insert into comics values("17", "Doomsday_Clock_Rebirth");
INSERT INTO Doomsday_Clock_Rebirth VALUES("283", "01", "Not Victory Nor Defeat", "", "2.99");
INSERT INTO Doomsday_Clock_Rebirth VALUES("286", "02", "Places We Have Never Known", "", "2.99");
INSERT INTO Doomsday_Clock_Rebirth VALUES("287", "03", "That Annihilated Place", "", "2.99");

insert into comics values("18", "Superwoman_Rebirth");
INSERT INTO Superwoman_Rebirth VALUES("141", "08", "By A Thread: Superwoman Reborn?", "Superman: Reborn", "2.99");
INSERT INTO Superwoman_Rebirth VALUES("150", "09", "Superman: Reborn Aftermath: Steel Resolve", "Superman: Reborn", "2.39");


insert into comics values("1", "Action_Comics_Rebirth");
INSERT INTO Action_Comics_Rebirth VALUES("2", "958", "Path of Doom Part 2", "", "2.99");
INSERT INTO Action_Comics_Rebirth VALUES("3", "957", "Path of Doom Part 1", "", "2.99");
INSERT INTO Action_Comics_Rebirth VALUES("45", "959", "Path of Doom Part 3", "", "2.99");
INSERT INTO Action_Comics_Rebirth VALUES("51", "960", "Path of Doom Part 4", "", "2.99");
INSERT INTO Action_Comics_Rebirth VALUES("52", "961", "Path of Doom Part 5", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("53", "962", "Path of Doom Conclusion", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("54", "963", "Superman, Meet Clark Kent Part 1", "", "1.49");
INSERT INTO Action_Comics_Rebirth VALUES("55", "964", "Superman, Meet Clark Kent Part 1", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("63", "965", "Lois Lane, Back At the Planet Part 1", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("64", "966", "Lois Lane, Back At the Planet Part 2", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("73", "967", "Men of Steel Part 1", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("74", "968", "Men of Steel Part 2", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("89", "969", "Men of Steel Part 3", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("90", "970", "Men of Steel Part 4", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("99", "971", "Men of Steel Part 5", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("100", "972", "Men of Steel Conclusion", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("113", "973", "Mild Mannered Part 1", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("114", "974", "Mild Mannered Part 2", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("128", "975", "Superman: Reborn Part 2: The Man in the Purple Hat", "Superman: Reborn", "1.99");
INSERT INTO Action_Comics_Rebirth VALUES("129", "976", "Superman: Reborn Part 4", "Superman: Reborn", "1.49");
INSERT INTO Action_Comics_Rebirth VALUES("145", "978", "The New World Part 2", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("156", "977", "The New World Part 1", "", "1.49");
INSERT INTO Action_Comics_Rebirth VALUES("171", "981", "Revenge Part 3", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("172", "982", "Revenge Part 4", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("175", "979", "Revenge Part 1", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("176", "980", "Revenge Part 2", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("196", "983", "Revenge Part 5", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("197", "984", "Revenge Conclusion", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("203", "985", "Only Human Part 1", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("204", "986", "Only Human Part 2: The Truth", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("214", "987", "The Oz Effect Part 1", "Oz Effect", "1.49");
INSERT INTO Action_Comics_Rebirth VALUES("215", "988", "The Oz Effect Part 2", "Oz Effect", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("230", "989", "The Oz Effect Part 3", "Oz Effect", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("231", "990", "The Oz Effect Part 4", "Oz Effect", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("243", "991", "The Oz Effect Conclusion", "Oz Effect", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("244", "992", "The Oz Effect Aftermath: Aftereffect", "Oz Effect", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("245", "993", "Booster Shot Part 1", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("246", "994", "Booster Shot Part 2", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("247", "995", "Booster Shot Part 3", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("248", "996", "Booster Shot Part 4", "", "1.79");
INSERT INTO Action_Comics_Rebirth VALUES("291", "1000", "", "", "7.99");

insert into comics values("2", "Batgirl_Rebirth");
INSERT INTO Batgirl_Rebirth VALUES("15", "02", "Beyond Burnside Part 2", "", "1.79");
INSERT INTO Batgirl_Rebirth VALUES("16", "03", "Beyond Burnside Part 3", "", "1.79");
INSERT INTO Batgirl_Rebirth VALUES("50", "01", "Beyond Burnside Part 1", "", "2.99");
INSERT INTO Batgirl_Rebirth VALUES("65", "04", "Beyond Burnsie Part 4", "", "1.79");
INSERT INTO Batgirl_Rebirth VALUES("75", "05", "Beyond Burnside Fianle", "", "1.79");
INSERT INTO Batgirl_Rebirth VALUES("86", "06", "Beyond Burnside Epilogue", "", "1.79");
INSERT INTO Batgirl_Rebirth VALUES("106", "07", "Son of Penguin Part 1", "", "1.79");
INSERT INTO Batgirl_Rebirth VALUES("123", "08", "Son of Penguin Part 2", "", "1.79");
INSERT INTO Batgirl_Rebirth VALUES("132", "09", "Son of Penguin Part 3", "", "1.79");
INSERT INTO Batgirl_Rebirth VALUES("146", "10", "Son of Penguin Part 4", "", "2.39");
INSERT INTO Batgirl_Rebirth VALUES("170", "12", "Troubled Waters", "", "2.39");
INSERT INTO Batgirl_Rebirth VALUES("177", "11", "Son of Penguin Finale", "", "2.39");
INSERT INTO Batgirl_Rebirth VALUES("199", "13", "The Truth About Bats and Dogs", "", "2.39");
INSERT INTO Batgirl_Rebirth VALUES("207", "14", "Summer of Lies Part 1", "", "1.79");
INSERT INTO Batgirl_Rebirth VALUES("221", "15", "Summer of Lies Part 2", "", "2.39");
INSERT INTO Batgirl_Rebirth VALUES("232", "16", "Summer of Lies Part 3", "", "2.39");
INSERT INTO Batgirl_Rebirth VALUES("255", "17", "Summer of Lies Finale", "", "2.39");
INSERT INTO Batgirl_Rebirth VALUES("256", "18", "White Elephant", "", "2.39");
INSERT INTO Batgirl_Rebirth VALUES("257", "19", "Cold Snap Part 1", "", "2.39");
INSERT INTO Batgirl_Rebirth VALUES("297", "23", "Strange Loop Part 2", "", "2.39");

insert into comics values("3", "Batman_Rebirth");
INSERT INTO Batman_Rebirth VALUES("17", "01", "I am Gotham Part 1", "", "2.99");
INSERT INTO Batman_Rebirth VALUES("18", "02", "I am Gotham Part 2", "", "2.99");
INSERT INTO Batman_Rebirth VALUES("19", "03", "I am Gotham Part 3", "", "2.99");
INSERT INTO Batman_Rebirth VALUES("20", "04", "I am Gotham Part 4", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("21", "05", "I am Gotham Part 5", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("22", "06", "I am Gotham Epilogue", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("23", "07", "Night of the Monster Men Part 1", "Monster Men", "1.79");
INSERT INTO Batman_Rebirth VALUES("61", "08", "Night of the Monster Men Part 4", "Monster Men", "1.79");
INSERT INTO Batman_Rebirth VALUES("62", "09", "I Am Suicide Part 1", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("76", "10", "I Am Suicide Part 2", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("77", "11", "I Am Suicide Part 3", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("97", "12", "I Am Suicide Part 4", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("98", "13", "I Am Suicide Part 5", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("109", "14", "Rooftops Part 1", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("110", "15", "Rooftops Part 2", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("117", "16", "I Am Bane Part 1", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("118", "17", "I Am Bane Part 2", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("134", "18", "I Am Bane Part 3", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("135", "19", "I Am Bane Part 4", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("143", "21", "The Button Part 1", "The Button", "1.79");
INSERT INTO Batman_Rebirth VALUES("154", "20", "I Am Bane Part 5", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("168", "24", "Every Epilogue Is A Prelude", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("169", "25", "The War of Jokes and Riddles Part 1", "", "2.39");
INSERT INTO Batman_Rebirth VALUES("178", "23", "The Brave and the Mold", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("194", "26", "The War of Jokes and Riddles Part 2", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("195", "27", "The War of Jokes and Riddles Interlude: The Ballad of Kite Man Part 1", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("205", "28", "The War of Jokes and Riddles Part 3", "", "2.39");
INSERT INTO Batman_Rebirth VALUES("206", "29", "The War of Jokes and Riddles Part 4", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("217", "30", "The War of Jokes and Riddles Interlude: The Ballad of Kite Man Part 2", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("218", "31", "The War of Jokes and Riddles Part 5", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("233", "32", "The War of Jokes & Riddles Conclusion", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("234", "33", "The Rules of Engagement Part 1", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("249", "34", "Rules of Engagement, Part 2", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("250", "35", "Rules of Engagement, Part 3", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("251", "36", "Superfriends Part 1", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("252", "37", "Superfriends Part 2", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("253", "38", "The Origin of Bruce Wayne", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("254", "39", "Superfriends Part 3", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("294", "46", "The Gift Part 2", "", "1.79");
INSERT INTO Batman_Rebirth VALUES("295", "47", "The Gift Finale", "", "1.79");

insert into comics values("6", "Green_Lanterns_Rebirth");
INSERT INTO Green_Lanterns_Rebirth VALUES("24", "01", "Rage Planet Part 1", "", "2.99");
INSERT INTO Green_Lanterns_Rebirth VALUES("25", "02", "Rage Planet Part 2", "", "2.99");
INSERT INTO Green_Lanterns_Rebirth VALUES("26", "04", "Rage Planet Part 4", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("27", "05", "Rage Planet Part 5", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("28", "06", "Rage Planet Part 6", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("29", "07", "Family Matters Part 1: Kitchen Nightmares", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("49", "03", "Rage Planet Part 3", "", "2.99");
INSERT INTO Green_Lanterns_Rebirth VALUES("66", "08", "Family Matters Part 2: All Hallows' Eve", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("67", "09", "The Phantom Lantern: Prologue", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("78", "10", "The Phantom Lantern: Part 1", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("79", "11", "The Phantom Lantern: Part 2", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("95", "12", "The Phantom Lantern Part 3", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("96", "13", "The Phantom Lantern Part 4", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("101", "14", "The Phantom Lantern Part 5", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("102", "15", "A Day in the Life", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("115", "16", "Darkest Knights Part 1", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("116", "17", "Darkest Knights Part 2", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("139", "18", "The Last Testament of the First Lantern", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("140", "19", "Polarity Chapter 1", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("152", "21", "Polarity Chapter 3: Flatline", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("155", "20", "Polarity Chapter 2: Drowning", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("166", "24", "Lost in Space Conclusion", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("167", "25", "The Return of the First Lanern", "", "2.39");
INSERT INTO Green_Lanterns_Rebirth VALUES("180", "22", "Lost in Space Part 1", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("181", "23", "Lost in Space Part 2", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("192", "26", "The First Ring", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("193", "27", "Out of Time Part 1: Homeworld", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("208", "28", "Out of Time Part 2: Miracles", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("209", "29", "Out of Time Part 3: United", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("219", "30", "Out of Time Part 4: Never Quit", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("220", "31", "Out of Time Finale: Homecoming", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("235", "32", "House Party", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("236", "33", "Work Release Part 1", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("258", "34", "Work Release Part 2", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("259", "35", "Oh, Bolphunga, Where Art Thou? Part 1", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("260", "36", "Oh, Bolphunga, Where Art Thou? Part 2", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("261", "37", "A World of Out Own Part 1", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("262", "38", "A World of Out Own Part 2", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("263", "39", "A World of Out Own Finale", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("289", "46", "Ghosts of the Past Part 3: Haunted!", "", "1.79");
INSERT INTO Green_Lanterns_Rebirth VALUES("290", "47", "Ghosts of the Past Part 4: Long Road Home", "", "1.79");

insert into comics values("7", "Supergirl_Rebirth");
INSERT INTO Supergirl_Rebirth VALUES("30", "01", "Reign of the Cyborg Superman Part 1", "", "1.49");
INSERT INTO Supergirl_Rebirth VALUES("68", "02", "Reign of the Cyborg Superman Part 2", "", "1.79");
INSERT INTO Supergirl_Rebirth VALUES("80", "03", "Reign of the Cyborg Superman Part 3", "", "1.79");
INSERT INTO Supergirl_Rebirth VALUES("85", "04", "Reign of the Cyborg Superman Part 4", "", "1.79");
INSERT INTO Supergirl_Rebirth VALUES("111", "05", "Reign of the Cyborg Superman Part 5", "", "1.79");
INSERT INTO Supergirl_Rebirth VALUES("124", "06", "Reign of the Cyborg Superman Finale", "", "1.79");
INSERT INTO Supergirl_Rebirth VALUES("138", "07", "Mission: Mind", "", "1.79");
INSERT INTO Supergirl_Rebirth VALUES("157", "08", "Family of Tomorrow", "", "2.39");
INSERT INTO Supergirl_Rebirth VALUES("165", "10", "Escape From the Phantom Zone Part 2", "", "2.39");
INSERT INTO Supergirl_Rebirth VALUES("182", "09", "Escape From the Phantom Zone Part 1", "", "2.39");
INSERT INTO Supergirl_Rebirth VALUES("198", "11", "Escape From the Phnatom Zone Finale", "", "2.39");
INSERT INTO Supergirl_Rebirth VALUES("210", "12", "The Girl of No Tomorrow Part 1", "", "2.39");
INSERT INTO Supergirl_Rebirth VALUES("227", "13", "The Girl of No Tomorrow Part 3", "", "2.39");
INSERT INTO Supergirl_Rebirth VALUES("237", "14", "Heaven to Earth", "", "2.39");
INSERT INTO Supergirl_Rebirth VALUES("276", "15", "Plain Sight Part 1", "", "2.39");
INSERT INTO Supergirl_Rebirth VALUES("277", "16", "Plain Sight Part 2", "", "2.39");
INSERT INTO Supergirl_Rebirth VALUES("278", "17", "Plain Sight Part 3", "", "2.39");

insert into comics values("8", "Superman_Rebirth");
INSERT INTO Superman_Rebirth VALUES("31", "01", "Son of Superman Part 1", "", "2.99");
INSERT INTO Superman_Rebirth VALUES("32", "02", "Son of Superman Part 2", "", "2.99");
INSERT INTO Superman_Rebirth VALUES("33", "04", "Son of Superman Part 4", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("34", "05", "Son of Superman Part 5", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("35", "06", "Son of Superman Part 6", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("36", "07", "Son of Superman Part 7: Our Town", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("48", "03", "Son of Superman Part 3", "", "2.99");
INSERT INTO Superman_Rebirth VALUES("69", "08", "Escape From Dinosaur Island Part 1", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("70", "09", "Escape From Dinosaur Island Part 2", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("83", "10", "In the Name of the Father: World's Smallest Part 1", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("84", "11", "In the Name of the Father: World's Smallest Part 2", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("93", "12", "Super-Monster Part 1", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("94", "13", "Super-Monster Part 2", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("107", "14", "Multiplicity Part 1", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("108", "15", "Multiplicity Part 2", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("119", "16", "Multiplicity Conclusion", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("120", "17", "Dark Harvest", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("130", "18", "Superman: Reborn Part 1", "Superman: Reborn ", "1.49");
INSERT INTO Superman_Rebirth VALUES("131", "19", "Superman: Reborn Part 3: Don't Pass Go", "Superman: Reborn", "1.49");
INSERT INTO Superman_Rebirth VALUES("149", "21", "Black Dawn Chapter 2", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("153", "20", "Black Dawn Chapter 1", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("163", "24", "Black Dawn Chapter 5", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("164", "25", "Black Dawn Chapter 6: Fade to Black", "", "2.39");
INSERT INTO Superman_Rebirth VALUES("183", "22", "Black Dawn Chapter 3", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("184", "23", "Black Dawn Chapter 4", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("189", "26", "Brain vs. Brawn", "", "2.99");
INSERT INTO Superman_Rebirth VALUES("190", "27", "Declaration Part 1", "Declaration", "1.79");
INSERT INTO Superman_Rebirth VALUES("191", "27", "Declaration Part 1", "Declaration", "1.79");
INSERT INTO Superman_Rebirth VALUES("211", "28", "Independence Day", "Declaration", "1.79");
INSERT INTO Superman_Rebirth VALUES("212", "29", "A Minute Longer Part 1", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("222", "30", "A Minute Longer Part 2: Hopes & Fears", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("223", "31", "Breaking Point Part 1", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("238", "32", "Breaking Point Part 2", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("239", "33", "Imperius Lex Part 1: The Superman Who Would Be King", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("264", "34", "Imperius Lex Part 2: Fire and Furries", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("265", "35", "Imperius Lex Part 3: World of Flame", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("266", "36", "Imperius Lex Part 4: Liberation", "", "1.79");
INSERT INTO Superman_Rebirth VALUES("267", "37", "Super Sons of Tomorrow Part 1: Dark of the Son", "Sons of Tomorrow", "3.00");
INSERT INTO Superman_Rebirth VALUES("268", "38", "Super Sons of Tomorrow Part 4: Into the Light", "Sons of Tomorrow", "1.79");
INSERT INTO Superman_Rebirth VALUES("269", "39", "Goodnight Moon", "", "1.79");

insert into comics values("10", "Wonder_Woman_Rebirth");
INSERT INTO Wonder_Woman_Rebirth VALUES("38", "01", "The Lies  Part 1", "", "2.99");
INSERT INTO Wonder_Woman_Rebirth VALUES("39", "02", "Year One Part 1", "", "2.99");
INSERT INTO Wonder_Woman_Rebirth VALUES("40", "03", "The Lies Part 2", "", "2.99");
INSERT INTO Wonder_Woman_Rebirth VALUES("41", "04", "Year One Part 2", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("42", "05", "The Lies Part 3", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("43", "06", "Year One Part 3", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("44", "07", "The Lies Part 4", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("71", "08", "Year One Interlude", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("72", "09", "The Lies Part 5", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("81", "10", "Year One Part 4", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("82", "11", "The Lies Conclusion", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("91", "12", "Year One Part 5", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("92", "13", "Angel Down", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("104", "14", "Year One Finale", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("105", "15", "The Truth Part 1", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("121", "16", "Godwatch Part 1", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("122", "17", "The Truth Part 2", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("136", "18", "Godwatch Part 2", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("137", "19", "The Truth Part 3", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("148", "21", "The Truth Part 4", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("158", "20", "Godwatch Part 3", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("160", "24", "Godwatch Epilogue", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("161", "25", "Perfect", "", "2.39");
INSERT INTO Wonder_Woman_Rebirth VALUES("187", "22", "Godwatch Part 4", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("188", "23", "The Truth Conclusion", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("201", "26", "Heart of the Amazon Part 1", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("202", "27", "Heart of the Amazon Part 2", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("213", "28", "Heart of the Amazon Part 3", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("224", "29", "Heart of the Amazon Part 4", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("225", "30", "Heart of the Amazon Part 5", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("226", "31", "Children of the Gods Part 1", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("241", "32", "Children of the Gods Part 2", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("242", "33", "Times Past Part 1: Grail", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("270", "34", "Children of the Gods Part 3", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("271", "35", "Times Past Part 2: Jason", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("272", "36", "Children of the Gods Part 4", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("273", "37", "Children of the Gods Conclusion", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("274", "38", "Swan's Song Part 1", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("275", "39", "Swan's Song Part 2", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("298", "46", "The Dark Gods Part 1", "", "1.79");
INSERT INTO Wonder_Woman_Rebirth VALUES("299", "47", "The Dark Gods Part 2", "", "1.79");

insert into comics values("13", "Teen_Titans_Rebirth");
INSERT INTO Teen_Titans_Rebirth VALUES("87", "03", "Damian Knows Best Part 3", "", "1.79");
INSERT INTO Teen_Titans_Rebirth VALUES("103", "04", "Damian Knows Best Part 4", "", "1.79");
INSERT INTO Teen_Titans_Rebirth VALUES("125", "01", "Damian Knows Best Part 1", "", "2.99");
INSERT INTO Teen_Titans_Rebirth VALUES("126", "02", "Damian Knows Best Part 2", "", "2.99");
INSERT INTO Teen_Titans_Rebirth VALUES("127", "05", "Damian Knows Best Part 5", "", "1.79");
INSERT INTO Teen_Titans_Rebirth VALUES("133", "06", "The Rise of Aqualad Part 1", "", "1.79");
INSERT INTO Teen_Titans_Rebirth VALUES("147", "07", "The Rise of Aqualad Finale", "", "2.39");
INSERT INTO Teen_Titans_Rebirth VALUES("162", "09", "Blood of the Manta Part 1", "", "2.39");
INSERT INTO Teen_Titans_Rebirth VALUES("185", "08", "The Lazarus Contract Part 2", "Lazarus Contract", "2.39");
INSERT INTO Teen_Titans_Rebirth VALUES("200", "10", "Blood of the Manta Part 2: The Secret Lives of Parents", "", "2.39");
INSERT INTO Teen_Titans_Rebirth VALUES("228", "11", "Blood of  the Manta Part 3", "", "4.47");
INSERT INTO Teen_Titans_Rebirth VALUES("229", "12", "Gotham Resistance Part 1", "Dark Knights: Metal", "2.39");
INSERT INTO Teen_Titans_Rebirth VALUES("240", "13", "Return of the Kid Flash Part 1", "", "2.39");
INSERT INTO Teen_Titans_Rebirth VALUES("279", "14", "The Return of Kid Flash Finale", "", "2.39");
INSERT INTO Teen_Titans_Rebirth VALUES("280", "15", "Super Sons of Tomorrow Part 3: Tomorrow is Never Promised", "Sons of Tomorrow", "2.39");
INSERT INTO Teen_Titans_Rebirth VALUES("281", "16", "Alone Against the World", "", "2.39");
